Integrity check (#132)
* Integrity check

* Improve message

* Add integrity to lint action

Co-authored-by: Frédéric Collonval <fcollonval@gmail.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -65,6 +65,18 @@ jobs:
         run: |
           yarn lint:check
 
+      - name: Integrity check
+        if: ${{ !contains(matrix.os, 'windows') }}
+        working-directory: javascript
+        run: |
+          set -ex
+          yarn integrity
+          if [[ $(git ls-files --exclude-standard -m | wc -l) > 0 ]]
+          then
+            echo "Integrity test failed; please run locally 'yarn integrity' and commit the changes"
+            exit 1
+          fi
+
       - name: Run Python tests
         run: |
           pytest -v
